
using FfxiParseToRules;

var sourceDir = "..\\..\\..\\..\\..\\VieweD Legacy\\data\\ffxi\\parse\\";
var outFile = "..\\..\\..\\..\\..\\VieweD dotNET6\\data\\ffxi\\rules\\converted.xml";
var xmlString = string.Empty;
var xmlIncoming = string.Empty;
var xmlOutgoing = string.Empty;

void ConvertFile(string filePath)
{
    var fileName = Path.GetFileNameWithoutExtension(filePath).ToLower();
    var packetIdString = fileName.Substring(fileName.IndexOf('x')+1);
    var packetDescription = string.Empty;
    var packetComment = string.Empty;
    var packetCredits = "ParseToRules";

    var data = string.Empty;

    var lines = File.ReadAllLines(filePath);
    foreach (var line in lines)
    {
        var newLine = ffxihelper.ConvertLine(line);
        if (newLine != string.Empty)
            data += newLine + "\n";
        if (ffxihelper.FileDescription != string.Empty)
            packetComment = ffxihelper.FileDescription;
        if (ffxihelper.FilePacketName != string.Empty)
            packetDescription = ffxihelper.FilePacketName;
    }


    var header = "<packet type=\"0x" + packetIdString + "\" desc=\""+packetDescription+"\" comment=\""+packetComment+"\" credits=\""+packetCredits+"\">\n";
    var footer = "</packet>\n";

    var res = header + data + footer;

    if (fileName.StartsWith("in-"))
        xmlIncoming += res;
    if (fileName.StartsWith("out-"))
        xmlOutgoing += res;

    // xmlString += res;
}


Console.WriteLine("FFXI Parse to Rules file converter");
Console.WriteLine("-----------------------------------");

var sourceFiles = Directory.GetFiles(sourceDir, "*-0x*.txt");
foreach (var sourceFile in sourceFiles)
{
    ConvertFile(sourceFile);
}

xmlString += "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
             "<!-- \n" +
             "This file was generated by FFXIParseToRules converter.\n" +
             "-->\n" +
             "<root>\n" +
             "\t<version client=\"\"/>\n" +
             "\t<templates>\n" +
             "\t</templates>\n" +
             "\t<tools>\n" +
             "\t</tools>\n" +
             "\t<rule>\n" +
             "\t\t<server port=\"0\"/>\n" +
             "\t\t<decryptor name=\"\"/>\n" +
             "\t\t<s2c>\n";
xmlString += xmlIncoming;
xmlString += "\t\t</s2c>\n" +
             "\t\t<c2s>\n";
xmlString += xmlOutgoing;
xmlString += "\t\t</c2s>\n" +
             "\t</rule>\n" +
             "</root>";

Console.WriteLine(xmlString);
File.WriteAllText(outFile, xmlString);
Console.ReadLine();