//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VieweD.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VieweD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7zip_x64 {
            get {
                object obj = ResourceManager.GetObject("7zip_x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_exit_16 {
            get {
                object obj = ResourceManager.GetObject("application-exit-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_menu_16 {
            get {
                object obj = ResourceManager.GetObject("application-menu-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        internal static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VieweD .NET 6.0.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_on_32 {
            get {
                object obj = ResourceManager.GetObject("audio_on_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_muted_32 {
            get {
                object obj = ResourceManager.GetObject("audio_volume_muted_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap auto_translate {
            get {
                object obj = ResourceManager.GetObject("auto-translate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only save projects that originate directly from a log file..
        /// </summary>
        internal static string CannotSaveVirtualProject {
            get {
                return ResourceManager.GetString("CannotSaveVirtualProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close {0} ?.
        /// </summary>
        internal static string CloseFile {
            get {
                return ResourceManager.GetString("CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cone_altglass_2_x48 {
            get {
                object obj = ResourceManager.GetObject("cone_altglass_2_x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm close.
        /// </summary>
        internal static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN .
        /// </summary>
        internal static string DirectionIn {
            get {
                return ResourceManager.GetString("DirectionIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT.
        /// </summary>
        internal static string DirectionOut {
            get {
                return ResourceManager.GetString("DirectionOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string DirectionUnknown {
            get {
                return ResourceManager.GetString("DirectionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discord_x32 {
            get {
                object obj = ResourceManager.GetObject("discord_x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_close_16 {
            get {
                object obj = ResourceManager.GetObject("document_close_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_decrypt_16 {
            get {
                object obj = ResourceManager.GetObject("document_decrypt_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_open_16 {
            get {
                object obj = ResourceManager.GetObject("document-open-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_open_32 {
            get {
                object obj = ResourceManager.GetObject("document-open-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_open_folder_16 {
            get {
                object obj = ResourceManager.GetObject("document-open-folder-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_properties_16 {
            get {
                object obj = ResourceManager.GetObject("document-properties-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_save_16 {
            get {
                object obj = ResourceManager.GetObject("document-save-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_save_all_16 {
            get {
                object obj = ResourceManager.GetObject("document-save-all-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_save_as_16 {
            get {
                object obj = ResourceManager.GetObject("document-save-as-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rules file.
        /// </summary>
        internal static string EditRulesFile {
            get {
                return ResourceManager.GetString("EditRulesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in rules file: 
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorInRulesFile {
            get {
                return ResourceManager.GetString("ErrorInRulesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open.
        /// </summary>
        internal static string FailedToOpen {
            get {
                return ResourceManager.GetString("FailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open {0} with error {1} .
        /// </summary>
        internal static string FailedToOpenUrl {
            get {
                return ResourceManager.GetString("FailedToOpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save rules file: {0}.
        /// </summary>
        internal static string FailedToSaveRulesFile {
            get {
                return ResourceManager.GetString("FailedToSaveRulesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load {0}\r\nException: {1}&quot;.
        /// </summary>
        internal static string FilterFailToLoad {
            get {
                return ResourceManager.GetString("FilterFailToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load filter error.
        /// </summary>
        internal static string FilterFailToLoadTitle {
            get {
                return ResourceManager.GetString("FilterFailToLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap github_mark {
            get {
                object obj = ResourceManager.GetObject("github-mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input reader error.
        /// </summary>
        internal static string InputReaderError {
            get {
                return ResourceManager.GetString("InputReaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kofi_p_logo_nolabel_x32 {
            get {
                object obj = ResourceManager.GetObject("kofi_p_logo_nolabel_x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current project was loaded from a lmog file or a older project format, you will need to save it into the new project format.
        /// </summary>
        internal static string LoadedOldProjectTypeAndNeedSave {
            get {
                return ResourceManager.GetString("LoadedOldProjectTypeAndNeedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_eject_32 {
            get {
                object obj = ResourceManager.GetObject("media_eject_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_playback_pause_32 {
            get {
                object obj = ResourceManager.GetObject("media_playback_pause_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_playback_start_32 {
            get {
                object obj = ResourceManager.GetObject("media_playback_start_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_playback_stop_32 {
            get {
                object obj = ResourceManager.GetObject("media_playback_stop_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_playlist_repeat_32 {
            get {
                object obj = ResourceManager.GetObject("media_playlist_repeat_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_playlist_shuffle_32 {
            get {
                object obj = ResourceManager.GetObject("media_playlist_shuffle_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_record_32 {
            get {
                object obj = ResourceManager.GetObject("media_record_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_seek_backward_32 {
            get {
                object obj = ResourceManager.GetObject("media_seek_backward_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_seek_forward_32 {
            get {
                object obj = ResourceManager.GetObject("media_seek_forward_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_skip_backward_32 {
            get {
                object obj = ResourceManager.GetObject("media_skip_backward_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_skip_forward_32 {
            get {
                object obj = ResourceManager.GetObject("media_skip_forward_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string MenuVersion {
            get {
                return ResourceManager.GetString("MenuVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini_in_icon {
            get {
                object obj = ResourceManager.GetObject("mini_in_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini_in_ticon {
            get {
                object obj = ResourceManager.GetObject("mini_in_ticon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini_out_icon {
            get {
                object obj = ResourceManager.GetObject("mini_out_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini_out_ticon {
            get {
                object obj = ResourceManager.GetObject("mini_out_ticon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini_unk_icon {
            get {
                object obj = ResourceManager.GetObject("mini_unk_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini_unk_ticon {
            get {
                object obj = ResourceManager.GetObject("mini_unk_ticon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini_video_icon {
            get {
                object obj = ResourceManager.GetObject("mini_video_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing rules file for project {0}.
        /// </summary>
        internal static string MissingRulesFileForProject {
            get {
                return ResourceManager.GetString("MissingRulesFileForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule attached to this packet, create a new one?.
        /// </summary>
        internal static string NoRuleAttachedToThisPacketCreateNewRule {
            get {
                return ResourceManager.GetString("NoRuleAttachedToThisPacketCreateNewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule data.
        /// </summary>
        internal static string NoRuleData {
            get {
                return ResourceManager.GetString("NoRuleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule found.
        /// </summary>
        internal static string NoRuleFound {
            get {
                return ResourceManager.GetString("NoRuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule linked to this packet.
        /// </summary>
        internal static string NoRuleLinkedToThisPacket {
            get {
                return ResourceManager.GetString("NoRuleLinkedToThisPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found!.
        /// </summary>
        internal static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        internal static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to search in!.
        /// </summary>
        internal static string NothingToSearch {
            get {
                return ResourceManager.GetString("NothingToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing packet data.
        /// </summary>
        internal static string ParsePackets {
            get {
                return ResourceManager.GetString("ParsePackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser Error.
        /// </summary>
        internal static string ParserError {
            get {
                return ResourceManager.GetString("ParserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating packet list, please wait ....
        /// </summary>
        internal static string PopulateListBox {
            get {
                return ResourceManager.GetString("PopulateListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        internal static string PopupCreateRule {
            get {
                return ResourceManager.GetString("PopupCreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0} =&gt; {1}.
        /// </summary>
        internal static string PopupEditRule {
            get {
                return ResourceManager.GetString("PopupEditRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string PopupInsert {
            get {
                return ResourceManager.GetString("PopupInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule assigned.
        /// </summary>
        internal static string PopupNoRuleAssigned {
            get {
                return ResourceManager.GetString("PopupNoRuleAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to edit.
        /// </summary>
        internal static string PopupNothingToEdit {
            get {
                return ResourceManager.GetString("PopupNothingToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string PopupReplace {
            get {
                return ResourceManager.GetString("PopupReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown direction, unable to edit.
        /// </summary>
        internal static string PopupUnknownDirection {
            get {
                return ResourceManager.GetString("PopupUnknownDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap project_open_16 {
            get {
                object obj = ResourceManager.GetObject("project-open-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Reading Error.
        /// </summary>
        internal static string ProjectReadingError {
            get {
                return ResourceManager.GetString("ProjectReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Error.
        /// </summary>
        internal static string RuleError {
            get {
                return ResourceManager.GetString("RuleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save cancelled.
        /// </summary>
        internal static string SaveCancelled {
            get {
                return ResourceManager.GetString("SaveCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search as New Tab.
        /// </summary>
        internal static string SearchAsNewTab {
            get {
                return ResourceManager.GetString("SearchAsNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        internal static string StatusNoEngine {
            get {
                return ResourceManager.GetString("StatusNoEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project folder: {0}.
        /// </summary>
        internal static string StatusProjectFolder {
            get {
                return ResourceManager.GetString("StatusProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project has been loaded.
        /// </summary>
        internal static string StatusProjectFolderNotLoaded {
            get {
                return ResourceManager.GetString("StatusProjectFolderNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string TypeUnknown {
            get {
                return ResourceManager.GetString("TypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to find a suitable reader for this file.
        /// </summary>
        internal static string UnableToFindInputReader {
            get {
                return ResourceManager.GetString("UnableToFindInputReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find parser.
        /// </summary>
        internal static string UnableToFindParser {
            get {
                return ResourceManager.GetString("UnableToFindParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open {0}.
        /// </summary>
        internal static string UnableToOpenFile {
            get {
                return ResourceManager.GetString("UnableToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open project file {0}.
        /// </summary>
        internal static string UnableToOpenProject {
            get {
                return ResourceManager.GetString("UnableToOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap usgaiji_10 {
            get {
                object obj = ResourceManager.GetObject("usgaiji-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap usgaiji_9 {
            get {
                object obj = ResourceManager.GetObject("usgaiji-9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_close_16 {
            get {
                object obj = ResourceManager.GetObject("view_close_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_hidden_16 {
            get {
                object obj = ResourceManager.GetObject("view_hidden_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_visible_16 {
            get {
                object obj = ResourceManager.GetObject("view_visible_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_close_16 {
            get {
                object obj = ResourceManager.GetObject("window_close_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wireshark_x48 {
            get {
                object obj = ResourceManager.GetObject("wireshark_x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
